#pragma once
#include <meta/macro/basic.hpp>
/*--------------------------------------------------
*                   Arithmetic                      |
*                 Public macros                     |
---------------------------------------------------*/

// increment(0~64)
#define META_INC(n) INTERNAL_META_INC(n)
// decrement(0~64)
#define META_DEC(n) INTERNAL_META_DEC(n)
#define META_EQUAL(x, y) INTERNAL_META_EQUAL(x, y)


/*--------------------------------------------------
*                   Arithmetic                      |
*            Internal macros(Dont use!)             |
---------------------------------------------------*/

// Internal for META_INC
#define INTERNAL_META_INC_0 1
#define INTERNAL_META_INC_1 2
#define INTERNAL_META_INC_2 3
#define INTERNAL_META_INC_3 4
#define INTERNAL_META_INC_4 5
#define INTERNAL_META_INC_5 6
#define INTERNAL_META_INC_6 7
#define INTERNAL_META_INC_7 8
#define INTERNAL_META_INC_8 9
#define INTERNAL_META_INC_9 10
#define INTERNAL_META_INC_10 11
#define INTERNAL_META_INC_11 12
#define INTERNAL_META_INC_12 13
#define INTERNAL_META_INC_13 14
#define INTERNAL_META_INC_14 15
#define INTERNAL_META_INC_15 16
#define INTERNAL_META_INC_16 17
#define INTERNAL_META_INC_17 18
#define INTERNAL_META_INC_18 19
#define INTERNAL_META_INC_19 20
#define INTERNAL_META_INC_20 21
#define INTERNAL_META_INC_21 22
#define INTERNAL_META_INC_22 23
#define INTERNAL_META_INC_23 24
#define INTERNAL_META_INC_24 25
#define INTERNAL_META_INC_25 26
#define INTERNAL_META_INC_26 27
#define INTERNAL_META_INC_27 28
#define INTERNAL_META_INC_28 29
#define INTERNAL_META_INC_29 30
#define INTERNAL_META_INC_30 31
#define INTERNAL_META_INC_31 32
#define INTERNAL_META_INC_32 33
#define INTERNAL_META_INC_33 34
#define INTERNAL_META_INC_34 35
#define INTERNAL_META_INC_35 36
#define INTERNAL_META_INC_36 37
#define INTERNAL_META_INC_37 38
#define INTERNAL_META_INC_38 39
#define INTERNAL_META_INC_39 40
#define INTERNAL_META_INC_40 41
#define INTERNAL_META_INC_41 42
#define INTERNAL_META_INC_42 43
#define INTERNAL_META_INC_43 44
#define INTERNAL_META_INC_44 45
#define INTERNAL_META_INC_45 46
#define INTERNAL_META_INC_46 47
#define INTERNAL_META_INC_47 48
#define INTERNAL_META_INC_48 49
#define INTERNAL_META_INC_49 50
#define INTERNAL_META_INC_50 51
#define INTERNAL_META_INC_51 52
#define INTERNAL_META_INC_52 53
#define INTERNAL_META_INC_53 54
#define INTERNAL_META_INC_54 55
#define INTERNAL_META_INC_55 56
#define INTERNAL_META_INC_56 57
#define INTERNAL_META_INC_57 58
#define INTERNAL_META_INC_58 59
#define INTERNAL_META_INC_59 60
#define INTERNAL_META_INC_60 61
#define INTERNAL_META_INC_61 62
#define INTERNAL_META_INC_62 63
#define INTERNAL_META_INC_63 64
#define INTERNAL_META_INC_64 65

#define INTERNAL_META_INC(n) META_CAT(INTERNAL_META_INC_, n)

// Internal for META_DEC
#define INTERNAL_META_DEC_0 -1
#define INTERNAL_META_DEC_1 0
#define INTERNAL_META_DEC_2 1
#define INTERNAL_META_DEC_3 2
#define INTERNAL_META_DEC_4 3
#define INTERNAL_META_DEC_5 4
#define INTERNAL_META_DEC_6 5
#define INTERNAL_META_DEC_7 6
#define INTERNAL_META_DEC_8 7
#define INTERNAL_META_DEC_9 8
#define INTERNAL_META_DEC_10 9
#define INTERNAL_META_DEC_11 10
#define INTERNAL_META_DEC_12 11
#define INTERNAL_META_DEC_13 12
#define INTERNAL_META_DEC_14 13
#define INTERNAL_META_DEC_15 14
#define INTERNAL_META_DEC_16 15
#define INTERNAL_META_DEC_17 16
#define INTERNAL_META_DEC_18 17
#define INTERNAL_META_DEC_19 18
#define INTERNAL_META_DEC_20 19
#define INTERNAL_META_DEC_21 20
#define INTERNAL_META_DEC_22 21
#define INTERNAL_META_DEC_23 22
#define INTERNAL_META_DEC_24 23
#define INTERNAL_META_DEC_25 24
#define INTERNAL_META_DEC_26 25
#define INTERNAL_META_DEC_27 26
#define INTERNAL_META_DEC_28 27
#define INTERNAL_META_DEC_29 28
#define INTERNAL_META_DEC_30 29
#define INTERNAL_META_DEC_31 30
#define INTERNAL_META_DEC_32 31
#define INTERNAL_META_DEC_33 32
#define INTERNAL_META_DEC_34 33
#define INTERNAL_META_DEC_35 34
#define INTERNAL_META_DEC_36 35
#define INTERNAL_META_DEC_37 36
#define INTERNAL_META_DEC_38 37
#define INTERNAL_META_DEC_39 38
#define INTERNAL_META_DEC_40 39
#define INTERNAL_META_DEC_41 40
#define INTERNAL_META_DEC_42 41
#define INTERNAL_META_DEC_43 42
#define INTERNAL_META_DEC_44 43
#define INTERNAL_META_DEC_45 44
#define INTERNAL_META_DEC_46 45
#define INTERNAL_META_DEC_47 46
#define INTERNAL_META_DEC_48 47
#define INTERNAL_META_DEC_49 48
#define INTERNAL_META_DEC_50 49
#define INTERNAL_META_DEC_51 50
#define INTERNAL_META_DEC_52 51
#define INTERNAL_META_DEC_53 52
#define INTERNAL_META_DEC_54 53
#define INTERNAL_META_DEC_55 54
#define INTERNAL_META_DEC_56 55
#define INTERNAL_META_DEC_57 56
#define INTERNAL_META_DEC_58 57
#define INTERNAL_META_DEC_59 58
#define INTERNAL_META_DEC_60 59
#define INTERNAL_META_DEC_61 60
#define INTERNAL_META_DEC_62 61
#define INTERNAL_META_DEC_63 62
#define INTERNAL_META_DEC_64 63

#define INTERNAL_META_DEC(n) META_CAT(INTERNAL_META_DEC_, n)

// Internal for META_EQUAL
#define INTERNAL_META_EQUAL_0_0 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_1_1 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_2_2 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_3_3 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_4_4 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_5_5 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_6_6 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_7_7 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_8_8 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_9_9 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_10_10 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_11_11 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_12_12 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_13_13 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_14_14 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_15_15 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_16_16 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_17_17 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_18_18 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_19_19 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_20_20 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_21_21 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_22_22 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_23_23 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_24_24 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_25_25 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_26_26 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_27_27 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_28_28 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_29_29 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_30_30 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_31_31 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_32_32 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_33_33 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_34_34 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_35_35 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_36_36 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_37_37 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_38_38 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_39_39 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_40_40 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_41_41 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_42_42 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_43_43 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_44_44 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_45_45 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_46_46 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_47_47 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_48_48 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_49_49 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_50_50 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_51_51 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_52_52 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_53_53 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_54_54 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_55_55 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_56_56 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_57_57 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_58_58 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_59_59 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_60_60 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_61_61 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_62_62 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_63_63 META_CHECK_TRUE
#define INTERNAL_META_EQUAL_64_64 META_CHECK_TRUE

#define INTERNAL_META_EQUAL_1(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_1_, x))
#define INTERNAL_META_EQUAL_2(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_2_, x))
#define INTERNAL_META_EQUAL_3(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_3_, x))
#define INTERNAL_META_EQUAL_4(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_4_, x))
#define INTERNAL_META_EQUAL_5(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_5_, x))
#define INTERNAL_META_EQUAL_6(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_6_, x))
#define INTERNAL_META_EQUAL_7(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_7_, x))
#define INTERNAL_META_EQUAL_8(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_8_, x))
#define INTERNAL_META_EQUAL_9(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_9_, x))
#define INTERNAL_META_EQUAL_10(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_10_, x))
#define INTERNAL_META_EQUAL_11(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_11_, x))
#define INTERNAL_META_EQUAL_12(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_12_, x))
#define INTERNAL_META_EQUAL_13(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_13_, x))
#define INTERNAL_META_EQUAL_14(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_14_, x))
#define INTERNAL_META_EQUAL_15(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_15_, x))
#define INTERNAL_META_EQUAL_16(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_16_, x))
#define INTERNAL_META_EQUAL_17(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_17_, x))
#define INTERNAL_META_EQUAL_18(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_18_, x))
#define INTERNAL_META_EQUAL_19(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_19_, x))
#define INTERNAL_META_EQUAL_20(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_20_, x))
#define INTERNAL_META_EQUAL_21(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_21_, x))
#define INTERNAL_META_EQUAL_22(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_22_, x))
#define INTERNAL_META_EQUAL_23(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_23_, x))
#define INTERNAL_META_EQUAL_24(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_24_, x))
#define INTERNAL_META_EQUAL_25(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_25_, x))
#define INTERNAL_META_EQUAL_26(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_26_, x))
#define INTERNAL_META_EQUAL_27(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_27_, x))
#define INTERNAL_META_EQUAL_28(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_28_, x))
#define INTERNAL_META_EQUAL_29(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_29_, x))
#define INTERNAL_META_EQUAL_30(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_30_, x))
#define INTERNAL_META_EQUAL_31(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_31_, x))
#define INTERNAL_META_EQUAL_32(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_32_, x))
#define INTERNAL_META_EQUAL_33(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_33_, x))
#define INTERNAL_META_EQUAL_34(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_34_, x))
#define INTERNAL_META_EQUAL_35(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_35_, x))
#define INTERNAL_META_EQUAL_36(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_36_, x))
#define INTERNAL_META_EQUAL_37(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_37_, x))
#define INTERNAL_META_EQUAL_38(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_38_, x))
#define INTERNAL_META_EQUAL_39(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_39_, x))
#define INTERNAL_META_EQUAL_40(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_40_, x))
#define INTERNAL_META_EQUAL_41(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_41_, x))
#define INTERNAL_META_EQUAL_42(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_42_, x))
#define INTERNAL_META_EQUAL_43(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_43_, x))
#define INTERNAL_META_EQUAL_44(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_44_, x))
#define INTERNAL_META_EQUAL_45(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_45_, x))
#define INTERNAL_META_EQUAL_46(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_46_, x))
#define INTERNAL_META_EQUAL_47(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_47_, x))
#define INTERNAL_META_EQUAL_48(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_48_, x))
#define INTERNAL_META_EQUAL_49(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_49_, x))
#define INTERNAL_META_EQUAL_50(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_50_, x))
#define INTERNAL_META_EQUAL_51(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_51_, x))
#define INTERNAL_META_EQUAL_52(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_52_, x))
#define INTERNAL_META_EQUAL_53(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_53_, x))
#define INTERNAL_META_EQUAL_54(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_54_, x))
#define INTERNAL_META_EQUAL_55(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_55_, x))
#define INTERNAL_META_EQUAL_56(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_56_, x))
#define INTERNAL_META_EQUAL_57(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_57_, x))
#define INTERNAL_META_EQUAL_58(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_58_, x))
#define INTERNAL_META_EQUAL_59(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_59_, x))
#define INTERNAL_META_EQUAL_60(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_60_, x))
#define INTERNAL_META_EQUAL_61(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_61_, x))
#define INTERNAL_META_EQUAL_62(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_62_, x))
#define INTERNAL_META_EQUAL_63(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_63_, x))
#define INTERNAL_META_EQUAL_64(x) META_CHECK(META_CAT(INTERNAL_META_EQUAL_64_, x))

#define INTERNAL_META_EQUAL(x, y) META_CAT(INTERNAL_META_EQUAL_, x)(y)