#pragma once
#include <meta/macro/basic.hpp>
/*--------------------------------------------------
*                     array                         |
*                 Public macros                     |
---------------------------------------------------*/

// Get the number of variable arguments
#define META_ARG_COUNT(...) INTERNAL_META_ARG_COUNT(__VA_ARGS__)
// Get the number of array
#define META_ARRAY_COUNT(array) META_ARG_COUNT(META_ARRAY_ELEMS(array))
// Get the subarray of an array(0 ~ count)
#define META_SUB_ARRAY(count, array) INTERNAL_META_RESERVE(count, META_ARRAY_ELEMS(array))



/*--------------------------------------------------
*                     array                         |
*            Internal macros(Dont use!)             |
---------------------------------------------------*/

// Internal for META_ARG_COUNT
#define INTERNAL_META_ARG_COUNT_IMPL(\
	 _0,  _1,  _2,  _3,  _4,  _5,  _6,  _7,  _8,  _9, \
	_10, _11, _12, _13, _14, _15, _16, _17, _18, _19, \
	_20, _21, _22, _23, _24, _25, _26, _27, _28, _29, \
	_30, _31, _32, _33, _34, _35, _36, _37, _38, _39, \
	_40, _41, _42, _43, _44, _45, _46, _47, _48, _49, \
	_50, _51, _52, _53, _54, _55, _56, _57, _58, _59, \
	_60, _61, _62, _63, _64, N, ...) N

#define INTERNAL_META_ARG_COUNT(...) META_EXPAND(INTERNAL_META_ARG_COUNT_IMPL(0, ##__VA_ARGS__,\
	64, 63, 62, 61, 60, \
	59, 58, 57, 56, 55, 54, 53, 52, 51, 50, \
	49, 48, 47, 46, 45, 44, 43, 42, 41, 40, \
	39, 38, 37, 36, 35, 34, 33, 32, 31, 30, \
	29, 28, 27, 26, 25, 24, 23, 22, 21, 20, \
	19, 18, 17, 16, 15, 14, 13, 12, 11, 10, \
	 9,  8,  7,  6,  5,  4,  3,  2,  1,  0))

// Internal for META_RESERVE
#define INTERNAL_META_RESERVE_0(...)
#define INTERNAL_META_RESERVE_1(n, ...) n
#define INTERNAL_META_RESERVE_2(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_1(__VA_ARGS__))
#define INTERNAL_META_RESERVE_3(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_2(__VA_ARGS__))
#define INTERNAL_META_RESERVE_4(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_3(__VA_ARGS__))
#define INTERNAL_META_RESERVE_5(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_4(__VA_ARGS__))
#define INTERNAL_META_RESERVE_6(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_5(__VA_ARGS__))
#define INTERNAL_META_RESERVE_7(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_6(__VA_ARGS__))
#define INTERNAL_META_RESERVE_8(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_7(__VA_ARGS__))
#define INTERNAL_META_RESERVE_9(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_8(__VA_ARGS__))
#define INTERNAL_META_RESERVE_10(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_9(__VA_ARGS__))
#define INTERNAL_META_RESERVE_11(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_10(__VA_ARGS__))
#define INTERNAL_META_RESERVE_12(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_11(__VA_ARGS__))
#define INTERNAL_META_RESERVE_13(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_12(__VA_ARGS__))
#define INTERNAL_META_RESERVE_14(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_13(__VA_ARGS__))
#define INTERNAL_META_RESERVE_15(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_14(__VA_ARGS__))
#define INTERNAL_META_RESERVE_16(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_15(__VA_ARGS__))
#define INTERNAL_META_RESERVE_17(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_16(__VA_ARGS__))
#define INTERNAL_META_RESERVE_18(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_17(__VA_ARGS__))
#define INTERNAL_META_RESERVE_19(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_18(__VA_ARGS__))
#define INTERNAL_META_RESERVE_20(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_19(__VA_ARGS__))
#define INTERNAL_META_RESERVE_21(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_20(__VA_ARGS__))
#define INTERNAL_META_RESERVE_22(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_21(__VA_ARGS__))
#define INTERNAL_META_RESERVE_23(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_22(__VA_ARGS__))
#define INTERNAL_META_RESERVE_24(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_23(__VA_ARGS__))
#define INTERNAL_META_RESERVE_25(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_24(__VA_ARGS__))
#define INTERNAL_META_RESERVE_26(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_25(__VA_ARGS__))
#define INTERNAL_META_RESERVE_27(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_26(__VA_ARGS__))
#define INTERNAL_META_RESERVE_28(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_27(__VA_ARGS__))
#define INTERNAL_META_RESERVE_29(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_28(__VA_ARGS__))
#define INTERNAL_META_RESERVE_30(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_29(__VA_ARGS__))
#define INTERNAL_META_RESERVE_31(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_30(__VA_ARGS__))
#define INTERNAL_META_RESERVE_32(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_31(__VA_ARGS__))
#define INTERNAL_META_RESERVE_33(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_32(__VA_ARGS__))
#define INTERNAL_META_RESERVE_34(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_33(__VA_ARGS__))
#define INTERNAL_META_RESERVE_35(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_34(__VA_ARGS__))
#define INTERNAL_META_RESERVE_36(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_35(__VA_ARGS__))
#define INTERNAL_META_RESERVE_37(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_36(__VA_ARGS__))
#define INTERNAL_META_RESERVE_38(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_37(__VA_ARGS__))
#define INTERNAL_META_RESERVE_39(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_38(__VA_ARGS__))
#define INTERNAL_META_RESERVE_40(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_39(__VA_ARGS__))
#define INTERNAL_META_RESERVE_41(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_40(__VA_ARGS__))
#define INTERNAL_META_RESERVE_42(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_41(__VA_ARGS__))
#define INTERNAL_META_RESERVE_43(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_42(__VA_ARGS__))
#define INTERNAL_META_RESERVE_44(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_43(__VA_ARGS__))
#define INTERNAL_META_RESERVE_45(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_44(__VA_ARGS__))
#define INTERNAL_META_RESERVE_46(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_45(__VA_ARGS__))
#define INTERNAL_META_RESERVE_47(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_46(__VA_ARGS__))
#define INTERNAL_META_RESERVE_48(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_47(__VA_ARGS__))
#define INTERNAL_META_RESERVE_49(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_48(__VA_ARGS__))
#define INTERNAL_META_RESERVE_50(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_49(__VA_ARGS__))
#define INTERNAL_META_RESERVE_51(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_50(__VA_ARGS__))
#define INTERNAL_META_RESERVE_52(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_51(__VA_ARGS__))
#define INTERNAL_META_RESERVE_53(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_52(__VA_ARGS__))
#define INTERNAL_META_RESERVE_54(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_53(__VA_ARGS__))
#define INTERNAL_META_RESERVE_55(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_54(__VA_ARGS__))
#define INTERNAL_META_RESERVE_56(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_55(__VA_ARGS__))
#define INTERNAL_META_RESERVE_57(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_56(__VA_ARGS__))
#define INTERNAL_META_RESERVE_58(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_57(__VA_ARGS__))
#define INTERNAL_META_RESERVE_59(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_58(__VA_ARGS__))
#define INTERNAL_META_RESERVE_60(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_59(__VA_ARGS__))
#define INTERNAL_META_RESERVE_61(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_60(__VA_ARGS__))
#define INTERNAL_META_RESERVE_62(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_61(__VA_ARGS__))
#define INTERNAL_META_RESERVE_63(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_62(__VA_ARGS__))
#define INTERNAL_META_RESERVE_64(n, ...) n, META_EXPAND(INTERNAL_META_RESERVE_63(__VA_ARGS__))

#define INTERNAL_META_RESERVE(count, ...) \
	META_EXPAND(META_CAT(INTERNAL_META_RESERVE_, count)(__VA_ARGS__))

#define INTERNAL_META_ARGS_INDEX_0(_0, ...) _0
#define INTERNAL_META_ARGS_INDEX_1(_0, _1, ...) _1
#define INTERNAL_META_ARGS_INDEX_2(_0, _1, _2, ...) _2
