#pragma once
#include <meta/macro/basic.hpp>
/*--------------------------------------------------
*                      Enum                         |
*                 Public macros                     |
---------------------------------------------------*/

#define META_SEQ_SIZE(seq) INTERNAL_META_SEQ_SIZE(seq)
// This macro expands to a comma-separated list of the elements in seq
// 
// Example:
// META_SEQ_ENUM((x)(y)(z)) expand to...
// x, y, z
#define META_SEQ_ENUM(seq) META_CAT(INTERNAL_META_SEQ_ENUM_, META_SEQ_SIZE(seq)) seq


/*--------------------------------------------------
*                      Enum                         |
*            Internal macros(Dont use!)             |
---------------------------------------------------*/

// Internal for META_SEQ_ENUM
# define INTERNAL_META_SEQ_ENUM_0(x)
# define INTERNAL_META_SEQ_ENUM_1(x) x
# define INTERNAL_META_SEQ_ENUM_2(x) x, INTERNAL_META_SEQ_ENUM_1
# define INTERNAL_META_SEQ_ENUM_3(x) x, INTERNAL_META_SEQ_ENUM_2
# define INTERNAL_META_SEQ_ENUM_4(x) x, INTERNAL_META_SEQ_ENUM_3
# define INTERNAL_META_SEQ_ENUM_5(x) x, INTERNAL_META_SEQ_ENUM_4
# define INTERNAL_META_SEQ_ENUM_6(x) x, INTERNAL_META_SEQ_ENUM_5
# define INTERNAL_META_SEQ_ENUM_7(x) x, INTERNAL_META_SEQ_ENUM_6
# define INTERNAL_META_SEQ_ENUM_8(x) x, INTERNAL_META_SEQ_ENUM_7
# define INTERNAL_META_SEQ_ENUM_9(x) x, INTERNAL_META_SEQ_ENUM_8
# define INTERNAL_META_SEQ_ENUM_10(x) x, INTERNAL_META_SEQ_ENUM_9
# define INTERNAL_META_SEQ_ENUM_11(x) x, INTERNAL_META_SEQ_ENUM_10
# define INTERNAL_META_SEQ_ENUM_12(x) x, INTERNAL_META_SEQ_ENUM_11
# define INTERNAL_META_SEQ_ENUM_13(x) x, INTERNAL_META_SEQ_ENUM_12
# define INTERNAL_META_SEQ_ENUM_14(x) x, INTERNAL_META_SEQ_ENUM_13
# define INTERNAL_META_SEQ_ENUM_15(x) x, INTERNAL_META_SEQ_ENUM_14
# define INTERNAL_META_SEQ_ENUM_16(x) x, INTERNAL_META_SEQ_ENUM_15
# define INTERNAL_META_SEQ_ENUM_17(x) x, INTERNAL_META_SEQ_ENUM_16
# define INTERNAL_META_SEQ_ENUM_18(x) x, INTERNAL_META_SEQ_ENUM_17
# define INTERNAL_META_SEQ_ENUM_19(x) x, INTERNAL_META_SEQ_ENUM_18
# define INTERNAL_META_SEQ_ENUM_20(x) x, INTERNAL_META_SEQ_ENUM_19
# define INTERNAL_META_SEQ_ENUM_21(x) x, INTERNAL_META_SEQ_ENUM_20
# define INTERNAL_META_SEQ_ENUM_22(x) x, INTERNAL_META_SEQ_ENUM_21
# define INTERNAL_META_SEQ_ENUM_23(x) x, INTERNAL_META_SEQ_ENUM_22
# define INTERNAL_META_SEQ_ENUM_24(x) x, INTERNAL_META_SEQ_ENUM_23
# define INTERNAL_META_SEQ_ENUM_25(x) x, INTERNAL_META_SEQ_ENUM_24
# define INTERNAL_META_SEQ_ENUM_26(x) x, INTERNAL_META_SEQ_ENUM_25
# define INTERNAL_META_SEQ_ENUM_27(x) x, INTERNAL_META_SEQ_ENUM_26
# define INTERNAL_META_SEQ_ENUM_28(x) x, INTERNAL_META_SEQ_ENUM_27
# define INTERNAL_META_SEQ_ENUM_29(x) x, INTERNAL_META_SEQ_ENUM_28
# define INTERNAL_META_SEQ_ENUM_30(x) x, INTERNAL_META_SEQ_ENUM_29
# define INTERNAL_META_SEQ_ENUM_31(x) x, INTERNAL_META_SEQ_ENUM_30
# define INTERNAL_META_SEQ_ENUM_32(x) x, INTERNAL_META_SEQ_ENUM_31
# define INTERNAL_META_SEQ_ENUM_33(x) x, INTERNAL_META_SEQ_ENUM_32
# define INTERNAL_META_SEQ_ENUM_34(x) x, INTERNAL_META_SEQ_ENUM_33
# define INTERNAL_META_SEQ_ENUM_35(x) x, INTERNAL_META_SEQ_ENUM_34
# define INTERNAL_META_SEQ_ENUM_36(x) x, INTERNAL_META_SEQ_ENUM_35
# define INTERNAL_META_SEQ_ENUM_37(x) x, INTERNAL_META_SEQ_ENUM_36
# define INTERNAL_META_SEQ_ENUM_38(x) x, INTERNAL_META_SEQ_ENUM_37
# define INTERNAL_META_SEQ_ENUM_39(x) x, INTERNAL_META_SEQ_ENUM_38
# define INTERNAL_META_SEQ_ENUM_40(x) x, INTERNAL_META_SEQ_ENUM_39
# define INTERNAL_META_SEQ_ENUM_41(x) x, INTERNAL_META_SEQ_ENUM_40
# define INTERNAL_META_SEQ_ENUM_42(x) x, INTERNAL_META_SEQ_ENUM_41
# define INTERNAL_META_SEQ_ENUM_43(x) x, INTERNAL_META_SEQ_ENUM_42
# define INTERNAL_META_SEQ_ENUM_44(x) x, INTERNAL_META_SEQ_ENUM_43
# define INTERNAL_META_SEQ_ENUM_45(x) x, INTERNAL_META_SEQ_ENUM_44
# define INTERNAL_META_SEQ_ENUM_46(x) x, INTERNAL_META_SEQ_ENUM_45
# define INTERNAL_META_SEQ_ENUM_47(x) x, INTERNAL_META_SEQ_ENUM_46
# define INTERNAL_META_SEQ_ENUM_48(x) x, INTERNAL_META_SEQ_ENUM_47
# define INTERNAL_META_SEQ_ENUM_49(x) x, INTERNAL_META_SEQ_ENUM_48
# define INTERNAL_META_SEQ_ENUM_50(x) x, INTERNAL_META_SEQ_ENUM_49
# define INTERNAL_META_SEQ_ENUM_51(x) x, INTERNAL_META_SEQ_ENUM_50
# define INTERNAL_META_SEQ_ENUM_52(x) x, INTERNAL_META_SEQ_ENUM_51
# define INTERNAL_META_SEQ_ENUM_53(x) x, INTERNAL_META_SEQ_ENUM_52
# define INTERNAL_META_SEQ_ENUM_54(x) x, INTERNAL_META_SEQ_ENUM_53
# define INTERNAL_META_SEQ_ENUM_55(x) x, INTERNAL_META_SEQ_ENUM_54
# define INTERNAL_META_SEQ_ENUM_56(x) x, INTERNAL_META_SEQ_ENUM_55
# define INTERNAL_META_SEQ_ENUM_57(x) x, INTERNAL_META_SEQ_ENUM_56
# define INTERNAL_META_SEQ_ENUM_58(x) x, INTERNAL_META_SEQ_ENUM_57
# define INTERNAL_META_SEQ_ENUM_59(x) x, INTERNAL_META_SEQ_ENUM_58
# define INTERNAL_META_SEQ_ENUM_60(x) x, INTERNAL_META_SEQ_ENUM_59
# define INTERNAL_META_SEQ_ENUM_61(x) x, INTERNAL_META_SEQ_ENUM_60
# define INTERNAL_META_SEQ_ENUM_62(x) x, INTERNAL_META_SEQ_ENUM_61
# define INTERNAL_META_SEQ_ENUM_63(x) x, INTERNAL_META_SEQ_ENUM_62
# define INTERNAL_META_SEQ_ENUM_64(x) x, INTERNAL_META_SEQ_ENUM_63


// Internal for META_SEQ_SIZE
# define INTERNAL_META_SEQ_SIZE_0(_) INTERNAL_META_SEQ_SIZE_1
# define INTERNAL_META_SEQ_SIZE_1(_) INTERNAL_META_SEQ_SIZE_2
# define INTERNAL_META_SEQ_SIZE_2(_) INTERNAL_META_SEQ_SIZE_3
# define INTERNAL_META_SEQ_SIZE_3(_) INTERNAL_META_SEQ_SIZE_4
# define INTERNAL_META_SEQ_SIZE_4(_) INTERNAL_META_SEQ_SIZE_5
# define INTERNAL_META_SEQ_SIZE_5(_) INTERNAL_META_SEQ_SIZE_6
# define INTERNAL_META_SEQ_SIZE_6(_) INTERNAL_META_SEQ_SIZE_7
# define INTERNAL_META_SEQ_SIZE_7(_) INTERNAL_META_SEQ_SIZE_8
# define INTERNAL_META_SEQ_SIZE_8(_) INTERNAL_META_SEQ_SIZE_9
# define INTERNAL_META_SEQ_SIZE_9(_) INTERNAL_META_SEQ_SIZE_10
# define INTERNAL_META_SEQ_SIZE_10(_) INTERNAL_META_SEQ_SIZE_11
# define INTERNAL_META_SEQ_SIZE_11(_) INTERNAL_META_SEQ_SIZE_12
# define INTERNAL_META_SEQ_SIZE_12(_) INTERNAL_META_SEQ_SIZE_13
# define INTERNAL_META_SEQ_SIZE_13(_) INTERNAL_META_SEQ_SIZE_14
# define INTERNAL_META_SEQ_SIZE_14(_) INTERNAL_META_SEQ_SIZE_15
# define INTERNAL_META_SEQ_SIZE_15(_) INTERNAL_META_SEQ_SIZE_16
# define INTERNAL_META_SEQ_SIZE_16(_) INTERNAL_META_SEQ_SIZE_17
# define INTERNAL_META_SEQ_SIZE_17(_) INTERNAL_META_SEQ_SIZE_18
# define INTERNAL_META_SEQ_SIZE_18(_) INTERNAL_META_SEQ_SIZE_19
# define INTERNAL_META_SEQ_SIZE_19(_) INTERNAL_META_SEQ_SIZE_20
# define INTERNAL_META_SEQ_SIZE_20(_) INTERNAL_META_SEQ_SIZE_21
# define INTERNAL_META_SEQ_SIZE_21(_) INTERNAL_META_SEQ_SIZE_22
# define INTERNAL_META_SEQ_SIZE_22(_) INTERNAL_META_SEQ_SIZE_23
# define INTERNAL_META_SEQ_SIZE_23(_) INTERNAL_META_SEQ_SIZE_24
# define INTERNAL_META_SEQ_SIZE_24(_) INTERNAL_META_SEQ_SIZE_25
# define INTERNAL_META_SEQ_SIZE_25(_) INTERNAL_META_SEQ_SIZE_26
# define INTERNAL_META_SEQ_SIZE_26(_) INTERNAL_META_SEQ_SIZE_27
# define INTERNAL_META_SEQ_SIZE_27(_) INTERNAL_META_SEQ_SIZE_28
# define INTERNAL_META_SEQ_SIZE_28(_) INTERNAL_META_SEQ_SIZE_29
# define INTERNAL_META_SEQ_SIZE_29(_) INTERNAL_META_SEQ_SIZE_30
# define INTERNAL_META_SEQ_SIZE_30(_) INTERNAL_META_SEQ_SIZE_31
# define INTERNAL_META_SEQ_SIZE_31(_) INTERNAL_META_SEQ_SIZE_32
# define INTERNAL_META_SEQ_SIZE_32(_) INTERNAL_META_SEQ_SIZE_33
# define INTERNAL_META_SEQ_SIZE_33(_) INTERNAL_META_SEQ_SIZE_34
# define INTERNAL_META_SEQ_SIZE_34(_) INTERNAL_META_SEQ_SIZE_35
# define INTERNAL_META_SEQ_SIZE_35(_) INTERNAL_META_SEQ_SIZE_36
# define INTERNAL_META_SEQ_SIZE_36(_) INTERNAL_META_SEQ_SIZE_37
# define INTERNAL_META_SEQ_SIZE_37(_) INTERNAL_META_SEQ_SIZE_38
# define INTERNAL_META_SEQ_SIZE_38(_) INTERNAL_META_SEQ_SIZE_39
# define INTERNAL_META_SEQ_SIZE_39(_) INTERNAL_META_SEQ_SIZE_40
# define INTERNAL_META_SEQ_SIZE_40(_) INTERNAL_META_SEQ_SIZE_41
# define INTERNAL_META_SEQ_SIZE_41(_) INTERNAL_META_SEQ_SIZE_42
# define INTERNAL_META_SEQ_SIZE_42(_) INTERNAL_META_SEQ_SIZE_43
# define INTERNAL_META_SEQ_SIZE_43(_) INTERNAL_META_SEQ_SIZE_44
# define INTERNAL_META_SEQ_SIZE_44(_) INTERNAL_META_SEQ_SIZE_45
# define INTERNAL_META_SEQ_SIZE_45(_) INTERNAL_META_SEQ_SIZE_46
# define INTERNAL_META_SEQ_SIZE_46(_) INTERNAL_META_SEQ_SIZE_47
# define INTERNAL_META_SEQ_SIZE_47(_) INTERNAL_META_SEQ_SIZE_48
# define INTERNAL_META_SEQ_SIZE_48(_) INTERNAL_META_SEQ_SIZE_49
# define INTERNAL_META_SEQ_SIZE_49(_) INTERNAL_META_SEQ_SIZE_50
# define INTERNAL_META_SEQ_SIZE_50(_) INTERNAL_META_SEQ_SIZE_51
# define INTERNAL_META_SEQ_SIZE_51(_) INTERNAL_META_SEQ_SIZE_52
# define INTERNAL_META_SEQ_SIZE_52(_) INTERNAL_META_SEQ_SIZE_53
# define INTERNAL_META_SEQ_SIZE_53(_) INTERNAL_META_SEQ_SIZE_54
# define INTERNAL_META_SEQ_SIZE_54(_) INTERNAL_META_SEQ_SIZE_55
# define INTERNAL_META_SEQ_SIZE_55(_) INTERNAL_META_SEQ_SIZE_56
# define INTERNAL_META_SEQ_SIZE_56(_) INTERNAL_META_SEQ_SIZE_57
# define INTERNAL_META_SEQ_SIZE_57(_) INTERNAL_META_SEQ_SIZE_58
# define INTERNAL_META_SEQ_SIZE_58(_) INTERNAL_META_SEQ_SIZE_59
# define INTERNAL_META_SEQ_SIZE_59(_) INTERNAL_META_SEQ_SIZE_60
# define INTERNAL_META_SEQ_SIZE_60(_) INTERNAL_META_SEQ_SIZE_61
# define INTERNAL_META_SEQ_SIZE_61(_) INTERNAL_META_SEQ_SIZE_62
# define INTERNAL_META_SEQ_SIZE_62(_) INTERNAL_META_SEQ_SIZE_63
# define INTERNAL_META_SEQ_SIZE_63(_) INTERNAL_META_SEQ_SIZE_64


# define INTERNAL_META_SEQ_SIZE_0_LITERAL 0
# define INTERNAL_META_SEQ_SIZE_1_LITERAL 1
# define INTERNAL_META_SEQ_SIZE_2_LITERAL 2
# define INTERNAL_META_SEQ_SIZE_3_LITERAL 3
# define INTERNAL_META_SEQ_SIZE_4_LITERAL 4
# define INTERNAL_META_SEQ_SIZE_5_LITERAL 5
# define INTERNAL_META_SEQ_SIZE_6_LITERAL 6
# define INTERNAL_META_SEQ_SIZE_7_LITERAL 7
# define INTERNAL_META_SEQ_SIZE_8_LITERAL 8
# define INTERNAL_META_SEQ_SIZE_9_LITERAL 9
# define INTERNAL_META_SEQ_SIZE_10_LITERAL 10
# define INTERNAL_META_SEQ_SIZE_11_LITERAL 11
# define INTERNAL_META_SEQ_SIZE_12_LITERAL 12
# define INTERNAL_META_SEQ_SIZE_13_LITERAL 13
# define INTERNAL_META_SEQ_SIZE_14_LITERAL 14
# define INTERNAL_META_SEQ_SIZE_15_LITERAL 15
# define INTERNAL_META_SEQ_SIZE_16_LITERAL 16
# define INTERNAL_META_SEQ_SIZE_17_LITERAL 17
# define INTERNAL_META_SEQ_SIZE_18_LITERAL 18
# define INTERNAL_META_SEQ_SIZE_19_LITERAL 19
# define INTERNAL_META_SEQ_SIZE_20_LITERAL 20
# define INTERNAL_META_SEQ_SIZE_21_LITERAL 21
# define INTERNAL_META_SEQ_SIZE_22_LITERAL 22
# define INTERNAL_META_SEQ_SIZE_23_LITERAL 23
# define INTERNAL_META_SEQ_SIZE_24_LITERAL 24
# define INTERNAL_META_SEQ_SIZE_25_LITERAL 25
# define INTERNAL_META_SEQ_SIZE_26_LITERAL 26
# define INTERNAL_META_SEQ_SIZE_27_LITERAL 27
# define INTERNAL_META_SEQ_SIZE_28_LITERAL 28
# define INTERNAL_META_SEQ_SIZE_29_LITERAL 29
# define INTERNAL_META_SEQ_SIZE_30_LITERAL 30
# define INTERNAL_META_SEQ_SIZE_31_LITERAL 31
# define INTERNAL_META_SEQ_SIZE_32_LITERAL 32
# define INTERNAL_META_SEQ_SIZE_33_LITERAL 33
# define INTERNAL_META_SEQ_SIZE_34_LITERAL 34
# define INTERNAL_META_SEQ_SIZE_35_LITERAL 35
# define INTERNAL_META_SEQ_SIZE_36_LITERAL 36
# define INTERNAL_META_SEQ_SIZE_37_LITERAL 37
# define INTERNAL_META_SEQ_SIZE_38_LITERAL 38
# define INTERNAL_META_SEQ_SIZE_39_LITERAL 39
# define INTERNAL_META_SEQ_SIZE_40_LITERAL 40
# define INTERNAL_META_SEQ_SIZE_41_LITERAL 41
# define INTERNAL_META_SEQ_SIZE_42_LITERAL 42
# define INTERNAL_META_SEQ_SIZE_43_LITERAL 43
# define INTERNAL_META_SEQ_SIZE_44_LITERAL 44
# define INTERNAL_META_SEQ_SIZE_45_LITERAL 45
# define INTERNAL_META_SEQ_SIZE_46_LITERAL 46
# define INTERNAL_META_SEQ_SIZE_47_LITERAL 47
# define INTERNAL_META_SEQ_SIZE_48_LITERAL 48
# define INTERNAL_META_SEQ_SIZE_49_LITERAL 49
# define INTERNAL_META_SEQ_SIZE_50_LITERAL 50
# define INTERNAL_META_SEQ_SIZE_51_LITERAL 51
# define INTERNAL_META_SEQ_SIZE_52_LITERAL 52
# define INTERNAL_META_SEQ_SIZE_53_LITERAL 53
# define INTERNAL_META_SEQ_SIZE_54_LITERAL 54
# define INTERNAL_META_SEQ_SIZE_55_LITERAL 55
# define INTERNAL_META_SEQ_SIZE_56_LITERAL 56
# define INTERNAL_META_SEQ_SIZE_57_LITERAL 57
# define INTERNAL_META_SEQ_SIZE_58_LITERAL 58
# define INTERNAL_META_SEQ_SIZE_59_LITERAL 59
# define INTERNAL_META_SEQ_SIZE_60_LITERAL 60
# define INTERNAL_META_SEQ_SIZE_61_LITERAL 61
# define INTERNAL_META_SEQ_SIZE_62_LITERAL 62
# define INTERNAL_META_SEQ_SIZE_63_LITERAL 63
# define INTERNAL_META_SEQ_SIZE_64_LITERAL 64

#define INTERNAL_META_SEQ_SIZE(seq) META_CAT(INTERNAL_META_SEQ_SIZE_0 seq, _LITERAL)