#pragma once
#include <meta/macro/array.hpp>
#include <meta/macro/arithmetic.hpp>
/*--------------------------------------------------
*                      For                          |
*                 Public macros                     |
---------------------------------------------------*/

#define META_FOREACH(f, ...) INTERNAL_META_FOREACH(f, __VA_ARGS__)

/*--------------------------------------------------
*                      For                          |
*            Internal macros(Dont use!)             |
---------------------------------------------------*/

// Internal for META_FOREACH
#define INTERNAL_META_FOR_0(i, f, arg, ...)
#define INTERNAL_META_FOR_1(i, f, arg, ...) f(i, arg)
#define INTERNAL_META_FOR_2(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_1(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_3(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_2(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_4(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_3(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_5(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_4(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_6(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_5(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_7(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_6(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_8(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_7(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_9(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_8(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_10(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_9(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_11(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_10(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_12(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_11(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_13(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_12(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_14(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_13(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_15(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_14(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_16(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_15(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_17(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_16(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_18(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_17(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_19(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_18(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_20(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_19(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_21(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_20(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_22(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_21(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_23(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_22(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_24(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_23(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_25(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_24(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_26(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_25(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_27(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_26(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_28(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_27(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_29(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_28(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_30(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_29(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_31(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_30(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_32(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_31(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_33(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_32(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_34(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_33(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_35(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_34(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_36(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_35(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_37(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_36(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_38(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_37(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_39(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_38(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_40(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_39(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_41(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_40(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_42(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_41(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_43(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_42(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_44(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_43(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_45(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_44(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_46(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_45(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_47(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_46(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_48(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_47(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_49(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_48(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_50(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_49(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_51(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_50(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_52(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_51(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_53(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_52(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_54(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_53(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_55(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_54(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_56(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_55(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_57(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_56(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_58(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_57(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_59(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_58(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_60(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_59(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_61(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_60(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_62(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_61(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_63(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_62(META_INC(i),f, __VA_ARGS__))
#define INTERNAL_META_FOR_64(i, f, arg, ...) f(i, arg) META_EXPAND(INTERNAL_META_FOR_63(META_INC(i),f, __VA_ARGS__))

#define INTERNAL_META_FOR(f, ...) \
	META_CAT(INTERNAL_META_FOR_, META_COUNT(__VA_ARGS__))(0, f, __VA_ARGS__)

#define INTERNAL_META_FOREACH_FOR_BLOCK_1(i, elem_array) META_ARRAY_INDEX(0, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_2(i, elem_array) META_ARRAY_INDEX(1, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_3(i, elem_array) META_ARRAY_INDEX(2, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_4(i, elem_array) META_ARRAY_INDEX(3, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_5(i, elem_array) META_ARRAY_INDEX(4, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_6(i, elem_array) META_ARRAY_INDEX(5, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_7(i, elem_array) META_ARRAY_INDEX(6, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_8(i, elem_array) META_ARRAY_INDEX(7, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_9(i, elem_array) META_ARRAY_INDEX(8, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_10(i, elem_array) META_ARRAY_INDEX(9, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_11(i, elem_array) META_ARRAY_INDEX(10, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_12(i, elem_array) META_ARRAY_INDEX(11, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_13(i, elem_array) META_ARRAY_INDEX(12, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_14(i, elem_array) META_ARRAY_INDEX(13, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_15(i, elem_array) META_ARRAY_INDEX(14, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_16(i, elem_array) META_ARRAY_INDEX(15, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_17(i, elem_array) META_ARRAY_INDEX(16, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_18(i, elem_array) META_ARRAY_INDEX(17, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_19(i, elem_array) META_ARRAY_INDEX(18, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_20(i, elem_array) META_ARRAY_INDEX(19, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_21(i, elem_array) META_ARRAY_INDEX(20, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_22(i, elem_array) META_ARRAY_INDEX(21, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_23(i, elem_array) META_ARRAY_INDEX(22, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_24(i, elem_array) META_ARRAY_INDEX(23, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_25(i, elem_array) META_ARRAY_INDEX(24, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_26(i, elem_array) META_ARRAY_INDEX(25, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_27(i, elem_array) META_ARRAY_INDEX(26, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_28(i, elem_array) META_ARRAY_INDEX(27, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_29(i, elem_array) META_ARRAY_INDEX(28, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_30(i, elem_array) META_ARRAY_INDEX(29, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_31(i, elem_array) META_ARRAY_INDEX(30, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_32(i, elem_array) META_ARRAY_INDEX(31, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_33(i, elem_array) META_ARRAY_INDEX(32, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_34(i, elem_array) META_ARRAY_INDEX(33, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_35(i, elem_array) META_ARRAY_INDEX(34, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_36(i, elem_array) META_ARRAY_INDEX(35, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_37(i, elem_array) META_ARRAY_INDEX(36, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_38(i, elem_array) META_ARRAY_INDEX(37, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_39(i, elem_array) META_ARRAY_INDEX(38, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_40(i, elem_array) META_ARRAY_INDEX(39, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_41(i, elem_array) META_ARRAY_INDEX(40, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_42(i, elem_array) META_ARRAY_INDEX(41, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_43(i, elem_array) META_ARRAY_INDEX(42, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_44(i, elem_array) META_ARRAY_INDEX(43, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_45(i, elem_array) META_ARRAY_INDEX(44, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_46(i, elem_array) META_ARRAY_INDEX(45, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_47(i, elem_array) META_ARRAY_INDEX(46, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_48(i, elem_array) META_ARRAY_INDEX(47, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_49(i, elem_array) META_ARRAY_INDEX(48, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_50(i, elem_array) META_ARRAY_INDEX(49, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_51(i, elem_array) META_ARRAY_INDEX(50, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_52(i, elem_array) META_ARRAY_INDEX(51, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_53(i, elem_array) META_ARRAY_INDEX(52, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_54(i, elem_array) META_ARRAY_INDEX(53, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_55(i, elem_array) META_ARRAY_INDEX(54, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_56(i, elem_array) META_ARRAY_INDEX(55, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_57(i, elem_array) META_ARRAY_INDEX(56, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_58(i, elem_array) META_ARRAY_INDEX(57, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_59(i, elem_array) META_ARRAY_INDEX(58, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_60(i, elem_array) META_ARRAY_INDEX(59, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_61(i, elem_array) META_ARRAY_INDEX(60, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_62(i, elem_array) META_ARRAY_INDEX(61, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_63(i, elem_array) META_ARRAY_INDEX(62, elem_array) ,
#define INTERNAL_META_FOREACH_FOR_BLOCK_64(i, elem_array) META_ARRAY_INDEX(63, elem_array) ,

#define INTERNAL_META_FOREACH_FOR_ARGS_N_I(n, ...) INTERNAL_META_FOR(META_CAT(INTERNAL_META_FOREACH_FOR_BLOCK_, n), __VA_ARGS__)
#define INTERNAL_META_FOREACH_FOR_ARGS_N(n, ...) META_RESERVE(META_COUNT(__VA_ARGS__), INTERNAL_META_FOREACH_FOR_ARGS_N_I(n, __VA_ARGS__))

#define INTERNAL_META_FOREACH_LV0(i, f, ...)
#define INTERNAL_META_FOREACH_LV1(i, f, ...) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(1, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV2(i, f, ...) INTERNAL_META_FOREACH_LV1(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(2, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV3(i, f, ...) INTERNAL_META_FOREACH_LV2(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(3, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV4(i, f, ...) INTERNAL_META_FOREACH_LV3(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(4, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV5(i, f, ...) INTERNAL_META_FOREACH_LV4(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(5, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV6(i, f, ...) INTERNAL_META_FOREACH_LV5(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(6, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV7(i, f, ...) INTERNAL_META_FOREACH_LV6(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(7, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV8(i, f, ...) INTERNAL_META_FOREACH_LV7(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(8, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV9(i, f, ...) INTERNAL_META_FOREACH_LV8(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(9, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV10(i, f, ...) INTERNAL_META_FOREACH_LV9(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(10, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV11(i, f, ...) INTERNAL_META_FOREACH_LV10(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(11, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV12(i, f, ...) INTERNAL_META_FOREACH_LV11(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(12, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV13(i, f, ...) INTERNAL_META_FOREACH_LV12(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(13, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV14(i, f, ...) INTERNAL_META_FOREACH_LV13(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(14, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV15(i, f, ...) INTERNAL_META_FOREACH_LV14(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(15, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV16(i, f, ...) INTERNAL_META_FOREACH_LV15(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(16, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV17(i, f, ...) INTERNAL_META_FOREACH_LV16(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(17, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV18(i, f, ...) INTERNAL_META_FOREACH_LV17(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(18, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV19(i, f, ...) INTERNAL_META_FOREACH_LV18(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(19, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV20(i, f, ...) INTERNAL_META_FOREACH_LV19(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(20, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV21(i, f, ...) INTERNAL_META_FOREACH_LV20(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(21, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV22(i, f, ...) INTERNAL_META_FOREACH_LV21(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(22, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV23(i, f, ...) INTERNAL_META_FOREACH_LV22(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(23, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV24(i, f, ...) INTERNAL_META_FOREACH_LV23(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(24, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV25(i, f, ...) INTERNAL_META_FOREACH_LV24(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(25, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV26(i, f, ...) INTERNAL_META_FOREACH_LV25(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(26, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV27(i, f, ...) INTERNAL_META_FOREACH_LV26(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(27, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV28(i, f, ...) INTERNAL_META_FOREACH_LV27(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(28, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV29(i, f, ...) INTERNAL_META_FOREACH_LV28(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(29, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV30(i, f, ...) INTERNAL_META_FOREACH_LV29(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(30, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV31(i, f, ...) INTERNAL_META_FOREACH_LV30(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(31, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV32(i, f, ...) INTERNAL_META_FOREACH_LV31(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(32, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV33(i, f, ...) INTERNAL_META_FOREACH_LV32(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(33, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV34(i, f, ...) INTERNAL_META_FOREACH_LV33(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(34, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV35(i, f, ...) INTERNAL_META_FOREACH_LV34(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(35, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV36(i, f, ...) INTERNAL_META_FOREACH_LV35(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(36, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV37(i, f, ...) INTERNAL_META_FOREACH_LV36(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(37, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV38(i, f, ...) INTERNAL_META_FOREACH_LV37(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(38, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV39(i, f, ...) INTERNAL_META_FOREACH_LV38(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(39, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV40(i, f, ...) INTERNAL_META_FOREACH_LV39(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(40, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV41(i, f, ...) INTERNAL_META_FOREACH_LV40(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(41, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV42(i, f, ...) INTERNAL_META_FOREACH_LV41(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(42, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV43(i, f, ...) INTERNAL_META_FOREACH_LV42(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(43, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV44(i, f, ...) INTERNAL_META_FOREACH_LV43(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(44, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV45(i, f, ...) INTERNAL_META_FOREACH_LV44(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(45, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV46(i, f, ...) INTERNAL_META_FOREACH_LV45(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(46, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV47(i, f, ...) INTERNAL_META_FOREACH_LV46(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(47, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV48(i, f, ...) INTERNAL_META_FOREACH_LV47(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(48, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV49(i, f, ...) INTERNAL_META_FOREACH_LV48(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(49, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV50(i, f, ...) INTERNAL_META_FOREACH_LV49(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(50, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV51(i, f, ...) INTERNAL_META_FOREACH_LV50(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(51, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV52(i, f, ...) INTERNAL_META_FOREACH_LV51(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(52, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV53(i, f, ...) INTERNAL_META_FOREACH_LV52(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(53, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV54(i, f, ...) INTERNAL_META_FOREACH_LV53(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(54, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV55(i, f, ...) INTERNAL_META_FOREACH_LV54(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(55, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV56(i, f, ...) INTERNAL_META_FOREACH_LV55(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(56, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV57(i, f, ...) INTERNAL_META_FOREACH_LV56(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(57, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV58(i, f, ...) INTERNAL_META_FOREACH_LV57(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(58, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV59(i, f, ...) INTERNAL_META_FOREACH_LV58(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(59, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV60(i, f, ...) INTERNAL_META_FOREACH_LV59(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(60, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV61(i, f, ...) INTERNAL_META_FOREACH_LV60(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(61, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV62(i, f, ...) INTERNAL_META_FOREACH_LV61(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(62, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV63(i, f, ...) INTERNAL_META_FOREACH_LV62(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(63, __VA_ARGS__))
#define INTERNAL_META_FOREACH_LV64(i, f, ...) INTERNAL_META_FOREACH_LV63(META_DEC(i), f, __VA_ARGS__) f(i, INTERNAL_META_FOREACH_FOR_ARGS_N(64, __VA_ARGS__))

#define INTERNAL_META_FOREACH_I(f, n, ...) META_CAT(INTERNAL_META_FOREACH_LV, n)(META_DEC(n), f, __VA_ARGS__)
#define INTERNAL_META_FOREACH(f, ...)						\
	 INTERNAL_META_FOREACH_I(f,								\
		META_ARRAY_COUNT(META_INDEX(0, __VA_ARGS__)),		\
		__VA_ARGS__)
